# Note: these tests depend on crates that use nightly features which do not
# run under stable and beta toolchains.
#
# Do not add these tests to the other tracing-futures tests unless the
# minimum Rust version is at least 1.36.
[workspace]

[package]
name = "test_std_future"
version = "0.1.0"
publish = false
edition = "2018"

[dependencies]
tokio-test = { git = "https://github.com/tokio-rs/tokio.git" }
tracing = { version = "0.1", path = "../../tracing" }
tracing-core = { version = "0.1.2", path = "../../tracing-core" }
tracing-futures = { path = "..", features = ["std-future"] }
